"""
PyPress — Alembic Migration Environment

This module configures how Alembic connects to the database and discovers
models. It supports both:
  - Online mode: connects to the DB and applies changes directly
  - Offline mode: generates SQL scripts without a DB connection

WordPress equivalent: WordPress's wp-admin/includes/upgrade.php which
runs dbDelta() — but Alembic's approach is versioned, reversible, and
doesn't try to diff schemas at runtime (which is fragile).
"""
import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

# ── Import the Base metadata ────────────────────────────────────────────
# This import triggers all model files to register their tables with
# SQLAlchemy's metadata registry. Alembic uses this metadata to generate
# migrations via `alembic revision --autogenerate`.
#
# IMPORTANT: Every new model file must be imported here (or transitively
# through app.models) for autogenerate to detect it.
from app.core.models import Base  # noqa: F401 — import triggers registration

# ── Alembic Config ──────────────────────────────────────────────────────
config = context.config

# Read the database URL from the environment variable (twelve-factor pattern).
# This overrides whatever is in alembic.ini, ensuring the migration connects
# to the correct database in every environment (dev, test, prod).
database_url = os.environ.get("DATABASE_URL")
if database_url:
    # Alembic needs the synchronous driver URL for some operations,
    # but we also support the async driver for online migrations.
    config.set_main_option("sqlalchemy.url", database_url)

# Set up Python logging from alembic.ini's [loggers] section
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The metadata object that Alembic uses to compare the desired schema
# (defined by our SQLAlchemy models) against the actual database schema.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode — generates SQL without connecting to DB.

    This is useful for:
      - Reviewing what SQL a migration will execute before running it
      - Generating SQL scripts for DBA review in enterprise environments
      - Environments where direct DB access isn't available

    Usage: alembic upgrade head --sql > migration.sql
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Include the object name in autogenerated migration operations
        # so migrations are self-documenting
        include_name=lambda name, type_, parent_names: True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    """Execute migrations against a live database connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # compare_type: detect column type changes (e.g., VARCHAR(50) → VARCHAR(100))
        compare_type=True,
        # compare_server_default: detect default value changes
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """
    Run migrations using an async engine — this is the production path.

    Creates an async engine from the DATABASE_URL, connects, and runs
    all pending migrations within a transaction.
    """
    configuration = config.get_section(config.config_ini_section, {})
    # Ensure the URL is set from environment
    if database_url:
        configuration["sqlalchemy.url"] = database_url

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # Don't pool connections during migrations
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode — connects to the actual database.

    This is the default mode when running `alembic upgrade head`.
    Uses asyncio because our SQLAlchemy setup uses async engines
    (asyncpg driver for PostgreSQL).
    """
    asyncio.run(run_async_migrations())


# ── Execute ──────────────────────────────────────────────────────────────
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
